python -m tasks.listops.train \
    --log_dir "logs/listops/run1"\
    --seed 1 \
    --iterations 75 \
    --memory_length 25 \
    --n_test_batches 20 \
    --d_model 120 \
    --d_input 128 \
    --n_synch_out 32 \
    --n_synch_action 32 \
    --synapse_depth 1 \
    --heads 8 \
    --memory_hidden_dims 16 \
    --dropout 0.0 \
    --deep_memory \
    --no-do_normalisation \
    --positional_embedding_type="learned-1d" \
    --backbone_type="listops"\
    --no-full_eval \
    --weight_decay 0.0 \
    --gradient_clipping 0.9 \
    --use_scheduler \
    --scheduler_type "cosine" \
    --milestones 0 0 0 \
    --gamma 0 \
    --dataset "listops" \
    --batch_size 64 \
    --batch_size_test 256 \
    --lr 0.0002 \
    --training_iterations 200001 \
    --warmup_steps 500 \
    --track_every 10 \
    --save_every 20 \
    --no-reload \
    --no-reload_model_only \
    --no-use_amp \
    --neuron_select_type "random" \
    --postactivation_production 'kan' # MLP or linear for postactivation production

